name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: install tools 
        run: apt-get update && apt-get install -y build-essential binutils-arm-none-eabi git libpng-dev

      - run: git clone https://github.com/pret/agbcc
      - run: cd agbcc
      - run: ls